name: "Build Lenny on Push and Daily"

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
      
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: "Build and push Lenny container"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/innereq/containers/lenny-ui:latest